// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXFrZQgqyf3LJxEMJgrT7ij2NlcZJkjQ',
    appId: '1:1075502747076:android:0fd5daa6e3aec44df42891',
    messagingSenderId: '1075502747076',
    projectId: 'lumora-4fee0',
    storageBucket: 'lumora-4fee0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn9TK0yjxoXCnwsnaDsh_Xxra6G4i-JWY',
    appId: '1:1075502747076:ios:eae8485759565da7f42891',
    messagingSenderId: '1075502747076',
    projectId: 'lumora-4fee0',
    storageBucket: 'lumora-4fee0.firebasestorage.app',
    iosBundleId: 'com.lumora.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVINnKOR-t1C6rL5-QDK_cXFXG0Xo6V_s',
    appId: '1:1075502747076:web:425ab16760c18781f42891',
    messagingSenderId: '1075502747076',
    projectId: 'lumora-4fee0',
    authDomain: 'lumora-4fee0.firebaseapp.com',
    storageBucket: 'lumora-4fee0.firebasestorage.app',
    measurementId: 'G-JWX8C45LS2',
  );
}
